### ISSUE TITLE
The file names are too long

### ISSUE THREAD

**Issue by papyr** [LindaLawton/Google-Dotnet-Samples#15]
Hi, I am beginning to get file name too long errors on a bare C:\test\ folder

![image](https://cloud.githubusercontent.com/assets/12733414/21067238/ed360fd0-be37-11e6-94cf-29fd0c99b1bd.png)

**Comment by LindaLawton** [comment]
I think you should post your code on [stackoverflow ](http://stackoverflow.com/questions/tagged/google-api-dotnet-client)   that does not sound like an issue with one of my samples.

**Comment by ScaleOvenStove** [comment]
I am getting this when trying to clone with GitHub Desktop or Visual Studio 2015. Not the screenshot above but the clone fails due to to long of paths. I have tried to clone to C:\ direct and still errors out

**Comment by LindaLawton** [comment]
@ScaleOvenStove  have you tried with the newer version? https://github.com/LindaLawton/Google-Dotnet-Samples/tree/Genreated-samples1.0   I am not sure downloading the new version via Visual studio will really do anything as there are no project or solution files.

**Comment by ScaleOvenStove** [comment]
yes, that worked

**Comment by LindaLawton** [comment]
If you find issues with that version please let me know I will add them to my list.

**Comment by papyr** [comment]
i still have this problem, same msg on x64 win 10
