### ISSUE TITLE
Hi LindaLawton

### ISSUE THREAD

**Issue by MuneshThakur** [LindaLawton/Google-Dotnet-Samples#5]
I read your Project this is Extremely Good . actually I am New Beginner with Google Calender API. actually I want to Create Event and Get Appointment Using Web Credential . but I have no Idea How to do it. can you help me in figure out it.and How to pass User credential for the invoke Google Calender service  Please Help me Asap.

Thanks & Regards 
Munesh

**Comment by LindaLawton** [comment]
You should look though the [Google-calendar sample](https://github.com/LindaLawton/Google-Dotnet-Samples/tree/master/Google-Calendar)

You might want to try asking a question like this on [stackoverflow.com](stackoverflow.com)  tag it [google-api-dotnet-client](http://stackoverflow.com/questions/tagged/google-api-dotnet-client)
