### ISSUE TITLE
where is this .net client library

### ISSUE THREAD

**Issue by ghost** [LindaLawton/Google-Dotnet-Samples#7]
I downloaded https://github.com/google/google-api-dotnet-client and see nothing related to analytics.

**Comment by LindaLawton** [comment]
https://github.com/google/google-api-dotnet-client is the core library, the .dlls for each of the different APIs are built automatically from the discovery API so there isn't a project for them on GitHub.   

The package source code is available at:
https://developers.google.com/resources/api-libraries/download/analytics/v3/csharp
