### ISSUE TITLE
Google Authentication.

### ISSUE THREAD

**Issue by abhidotnet** [LindaLawton/Google-Dotnet-Samples#8]
Hi Linda,
Your blog is very good and I will be visiting it more often as I have just started working on Google Analytics.

I am using this code to get authenticated on Google. I am using a console based application written in C#. Everytime I call this, I invoke a browser and I have to hit accept on the google website. I am using the <b>Google.Apis.Auth.OAuth2</b> library available from Nuget.

The question I have is, how can I make use of the <b>stored token</b> instead of having to invoke the browser for each invocation of the program.

<pre>
private void Run()
        {
            UserCredential credential;
            using (var stream = new FileStream("client_secrets.json", FileMode.Open, FileAccess.Read))
            {
                credential = GoogleWebAuthorizationBroker.AuthorizeAsync(
                    GoogleClientSecrets.Load(stream).Secrets,
                    new[] { DriveService.Scope.Drive, DriveService.Scope.DriveFile, AnalyticsService.Scope.Analytics, AnalyticsService.Scope.AnalyticsReadonly },
                    Environment.UserName, CancellationToken.None, new FileDataStore("OAuthTokens.Store")).Result;
            }
}</pre>

Thank You,
Abhi

**Comment by LindaLawton** [comment]
You are using FileDataStore which stores the authentication code in %appData% basied upon the user sent "Environment.UserName".    So assuming you are using the same user it shouldn't prompt you to login again.  

You can create your own implementation of Idatastore and store the authentication where ever you like. I have a very old example of how to do it storing the refreshtoken in the database for example [databasedatastore.cs](https://github.com/LindaLawton/Google-Dotnet-Samples/blob/master/Authentication/Diamto.Google.Authentication/Diamto.Google.Authentication/DatabaseDataStore.cs)

You might want to try asking a question like this on [stackoverflow.com](stackoverflow.com)  tag it [google-api-dotnet-client](http://stackoverflow.com/questions/tagged/google-api-dotnet-client)

**Comment by abhidotnet** [comment]
Hi Linda,
Thank you for your detailed explanation. I have used a service account to create a login.

I do have a few questions on <a href="http://stackoverflow.com/search?q=user:360821+[google-analytics]">stackoverflow</a> that are outstanding.
